export const E2E_ID = {
  onboarding: {
    welcomeImportExisting: 'e2e.onboarding.welcome.import-existing',
    importMethodPrivateKey: 'e2e.onboarding.import-method.private-key',
    privateKeyTab: 'e2e.onboarding.private-key.tab',
    privateKeyInput: 'e2e.onboarding.private-key.input',
    privateKeySubmit: 'e2e.onboarding.private-key.submit',
    setPasswordInput: 'e2e.onboarding.set-password.password',
    setPasswordConfirmInput: 'e2e.onboarding.set-password.confirm-password',
    setPasswordBiometrics: 'e2e.onboarding.set-password.biometrics',
    setPasswordBiometricsOn: 'e2e.onboarding.set-password.biometrics.on',
    setPasswordBiometricsOff: 'e2e.onboarding.set-password.biometrics.off',
    setPasswordAgreement: 'e2e.onboarding.set-password.agreement',
    setPasswordSubmit: 'e2e.onboarding.set-password.submit',
    importSuccessPrimary: 'e2e.onboarding.import-success.primary',
  },
  unlock: {
    passwordInput: 'e2e.unlock.password.input',
    submit: 'e2e.unlock.submit',
    switchAuthType: 'e2e.unlock.switch-auth-type',
    switchAuthTypePassword: 'e2e.unlock.switch-auth-type.password',
    switchAuthTypeBiometrics: 'e2e.unlock.switch-auth-type.biometrics',
  },
  authModal: {
    passwordInput: 'e2e.auth-modal.password.input',
    cancelButton: 'e2e.auth-modal.cancel',
    confirmButton: 'e2e.auth-modal.confirm',
  },
  home: {
    addAddressButton: 'e2e.home.add-address.button',
    settingsButton: 'e2e.home.settings.button',
    addAddressImportAddress: 'e2e.home.add-address.import-address',
    importMethodWatchAddress: 'e2e.home.import-method.watch-address',
    portfolioBalanceValue: 'e2e.home.portfolio.balance.value',
    portfolioBalanceLoading: 'e2e.home.portfolio.balance.loading',
    portfolioChangeLoading: 'e2e.home.portfolio.change.loading',
    portfolioCurveLoading: 'e2e.home.portfolio.curve.loading',
    portfolioCurveToggle: 'e2e.home.portfolio.curve.toggle',
    watchAddressInput: 'e2e.home.watch-address.input',
    watchAddressEnsResult: 'e2e.home.watch-address.ens-result',
    watchAddressSubmit: 'e2e.home.watch-address.submit',
    singleBalanceValue: 'e2e.home.single-address.balance.value',
    singleBalanceLoading: 'e2e.home.single-address.balance.loading',
    singleChangeLoading: 'e2e.home.single-address.change.loading',
    singleCurveLoading: 'e2e.home.single-address.curve.loading',
    singleCurveToggle: 'e2e.home.single-address.curve.toggle',
    singleAddressBack: 'e2e.home.single-address.back',
  },
  settings: {
    uiPlayground: 'e2e.settings.ui-playground',
  },
  send: {
    screen: 'e2e.send.screen',
    fromSection: 'e2e.send.from.section',
    toSection: 'e2e.send.to.section',
    amountInput: 'e2e.send.amount.input',
    amountMax: 'e2e.send.amount.max',
    tokenSelector: 'e2e.send.token.selector',
    confirmButton: 'e2e.send.confirm.button',
  },
  playground: {
    components2024Entry: 'e2e.playground.components2024.entry',
    components2024Screen: 'e2e.playground.components2024.screen',
    components2024ButtonPrimary: 'e2e.playground.components2024.button.primary',
    components2024ButtonLoading: 'e2e.playground.components2024.button.loading',
    components2024ButtonPressCount:
      'e2e.playground.components2024.button.press-count',
    components2024ButtonLoadingState:
      'e2e.playground.components2024.button.loading-state',
    components2024CheckboxToggle:
      'e2e.playground.components2024.checkbox.toggle',
    components2024CheckboxState: 'e2e.playground.components2024.checkbox.state',
    components2024RadioAlpha: 'e2e.playground.components2024.radio.alpha',
    components2024RadioBeta: 'e2e.playground.components2024.radio.beta',
    components2024RadioState: 'e2e.playground.components2024.radio.state',
    components2024PillsContainer:
      'e2e.playground.components2024.pills.container',
    components2024PillsPortfolio:
      'e2e.playground.components2024.pills.portfolio',
    components2024PillsActivity: 'e2e.playground.components2024.pills.activity',
    components2024PillsState: 'e2e.playground.components2024.pills.state',
    components2024SearchInput: 'e2e.playground.components2024.search.input',
    components2024SearchState: 'e2e.playground.components2024.search.state',
  },
} as const;
