import React, { useCallback, useMemo } from 'react';
import { View, TouchableOpacity } from 'react-native';
import * as Yup from 'yup';
import { useTranslation } from 'react-i18next';
import { useTheme2024 } from '@/hooks/theme';
import { createGetStyles2024 } from '@/utils/styles';
import { NextInput } from '@/components2024/Form/Input';
import { Button } from '@/components2024/Button';
import {
  getFormikErrorsCount,
  useAppFormik,
  validateFormikSchema,
} from '@/utils/patch';
import { CheckBoxRect } from '@/components2024/CheckBox';
import { AppSwitch2024 } from '@/components/customized/Switch2024';
import { useBiometrics } from '@/hooks/biometrics';
import { Text } from '@/components/Typography';
import YesIcon from '@/assets2024/icons/common/check.svg';
import RcIconKeychainFaceIdCC from '@/assets2024/icons/common/fack_id.svg';
import RcIconKeychainFingerprintCC from '@/assets2024/icons/common/fingerprint.svg';
import { useShowUserAgreementLikeModal } from '@/screens/ManagePassword/components/UserAgreementLikeModalInner2024';
import { APP_TEST_PWD } from '@/constant';
import { E2E_ID } from '@/constant/e2e';
import { makeTestIDProps } from '@/utils/makeTestIDProps';

const INIT_FORM_DATA = __DEV__
  ? {
      password: APP_TEST_PWD,
      confirmPassword: APP_TEST_PWD,
      checked: true,
      enableBiometrics: false,
    }
  : {
      password: '',
      confirmPassword: '',
      checked: true,
      enableBiometrics: false,
    };

export interface PasswordFormValues {
  password: string;
  confirmPassword: string;
  checked: boolean;
  enableBiometrics: boolean;
  /** When true, password/confirmPassword are ignored — a random password is generated instead. */
  useAutoGeneratedPassword?: boolean;
}

export interface PasswordFormProps {
  /**
   * Called when form is submitted with valid values
   */
  onSubmit: (
    values: PasswordFormValues,
  ) => void | Promise<void | 'fallback' | 'success'>;
  /**
   * Optional initial values
   */
  initialValues?: Partial<PasswordFormValues>;
  /**
   * Optional button text
   */
  submitButtonTitle?: string;
  /**
   * Disable form submission
   */
  disabled?: boolean;
  /**
   * Optional top tip text
   */
  topTip?: string;
  /**
   * Show loading state on button
   */
  loading?: boolean;
}

export const PasswordForm: React.FC<PasswordFormProps> = ({
  onSubmit,
  initialValues = {},
  submitButtonTitle,
  disabled = false,
  topTip,
  loading = false,
}) => {
  const [showPasswordFallback, setShowPasswordFallback] = React.useState(false);
  const { t } = useTranslation();
  const { styles, colors2024 } = useTheme2024({ getStyle });
  const { viewTermsOfUse, viewPrivacyPolicy } = useShowUserAgreementLikeModal();

  const {
    computed: { defaultTypeLabel, couldSetupBiometrics, isFaceID },
  } = useBiometrics({ autoFetch: true });

  const isBiometricMode = couldSetupBiometrics && !showPasswordFallback;

  const mergedInitialValues = {
    ...INIT_FORM_DATA,
    ...initialValues,
  };

  const yupSchema = React.useMemo(() => {
    const passSchema = Yup.string()
      .default(mergedInitialValues.password)
      .required(t('page.createPassword.passwordRequired'))
      .min(8, t('page.nextComponent.createNewAddress.passwordMin'));

    return Yup.object({
      password: passSchema,
      confirmPassword: Yup.string()
        .default(mergedInitialValues.confirmPassword)
        .when('password', {
          is: (password: string) => passSchema.isValidSync(password),
          then: schema =>
            schema
              .required(t('page.createPassword.confirmRequired'))
              .oneOf(
                [Yup.ref('password')],
                t('page.createPassword.confirmError'),
              ),
        }),
      enableBiometrics: Yup.boolean().default(couldSetupBiometrics),
      checked: Yup.boolean().default(mergedInitialValues.checked).oneOf([true]),
    });
  }, [
    t,
    couldSetupBiometrics,
    mergedInitialValues.password,
    mergedInitialValues.confirmPassword,
    mergedInitialValues.checked,
  ]);

  const formik = useAppFormik({
    initialValues: yupSchema.getDefault(),
    validationSchema: yupSchema,
    validateOnMount: false,
    validateOnChange: false,
    onSubmit: async values => {
      const errors = formik.validateFormValues();
      if (getFormikErrorsCount(errors)) {
        return;
      }

      await onSubmit(values);
    },
  });

  const handleContinue = useCallback(() => {
    const validationResult = formik.validateFormValues();
    if (getFormikErrorsCount(validationResult)) {
      return;
    }
    formik.handleSubmit();
  }, [formik]);

  const handleBiometricContinue = useCallback(async () => {
    if (!formik.values.checked) return;
    const result = await onSubmit({
      password: '',
      confirmPassword: '',
      checked: formik.values.checked,
      enableBiometrics: true,
      useAutoGeneratedPassword: true,
    });
    if (result === 'fallback') {
      formik.setFieldValue('enableBiometrics', false);
      setShowPasswordFallback(true);
    }
  }, [formik, onSubmit]);

  // Memoize validation to avoid calling validateFormValues on every render
  const validationErrors = useMemo(
    () => validateFormikSchema(formik.values, yupSchema),
    [formik.values, yupSchema],
  );

  const isFormValueValid =
    formik.values.checked && !getFormikErrorsCount(validationErrors);

  const shouldDisabled = isBiometricMode
    ? !formik.values.checked || disabled
    : !isFormValueValid || disabled;

  const handlePress = isBiometricMode
    ? handleBiometricContinue
    : handleContinue;

  return (
    <View style={styles.container}>
      {!isBiometricMode && topTip && (
        <Text style={styles.topTipText}>{topTip}</Text>
      )}

      {!isBiometricMode && (
        <View style={styles.inputHorizontalGroup}>
          <NextInput.Password
            fieldName={t('page.createPassword.Newpassword')}
            fieldNameStyle={styles.absoluteLeft}
            inputStyle={styles.paddingLeft}
            containerStyle={styles.inputStyle}
            inputProps={{
              value: formik.values.password,
              secureTextEntry: true,
              inputMode: 'text',
              returnKeyType: 'done',
              placeholder: '',
              ...makeTestIDProps(E2E_ID.onboarding.setPasswordInput),
              onChangeText(text) {
                formik.setFieldValue('password', text, true);
              },
            }}
            hasError={Boolean(formik.errors.password)}
            tipText={
              formik.errors.password ||
              t('page.nextComponent.createNewAddress.passwordMin')
            }
            tipIcon={
              !formik.errors.password &&
              formik.values.password && <YesIcon width={12} height={12} />
            }
          />

          <NextInput.Password
            fieldName={t('page.createPassword.ConfirmPassword')}
            style={{ marginTop: 20 }}
            containerStyle={styles.inputStyle}
            fieldNameStyle={styles.absoluteLeft}
            inputStyle={styles.paddingLeft}
            inputProps={{
              value: formik.values.confirmPassword,
              secureTextEntry: true,
              inputMode: 'text',
              returnKeyType: 'done',
              placeholder: '',
              placeholderTextColor: colors2024['neutral-foot'],
              ...makeTestIDProps(E2E_ID.onboarding.setPasswordConfirmInput),
              onChangeText(text) {
                formik.setFieldValue('confirmPassword', text, true);
              },
            }}
            hasError={Boolean(
              formik.values.confirmPassword && formik.errors.confirmPassword,
            )}
            tipText={
              formik.values.confirmPassword && !formik.errors.password
                ? formik.errors.confirmPassword ||
                  t('page.nextComponent.createNewAddress.confirmPasswordTips')
                : undefined
            }
            tipIcon={
              !formik.errors.password &&
              formik.values.password &&
              !formik.errors.confirmPassword &&
              formik.values.confirmPassword && (
                <YesIcon width={12} height={12} />
              )
            }
          />
        </View>
      )}

      {!isBiometricMode && (
        <View
          style={[
            styles.switchContainer,
            !couldSetupBiometrics && styles.switchContainerDisabled,
          ]}>
          <Text style={styles.labelText}>
            {t('page.createPassword.enable', { bioType: defaultTypeLabel })}
          </Text>
          <View style={styles.valueView}>
            <AppSwitch2024
              value={formik.values.enableBiometrics}
              disabled={!couldSetupBiometrics}
              {...makeTestIDProps(
                E2E_ID.onboarding.setPasswordBiometrics,
                formik.values.enableBiometrics
                  ? E2E_ID.onboarding.setPasswordBiometricsOn
                  : E2E_ID.onboarding.setPasswordBiometricsOff,
              )}
              onValueChange={async value => {
                formik.setFieldValue('enableBiometrics', value, true);
              }}
            />
          </View>
        </View>
      )}

      {/* Spacer between switch and agreement */}
      <View style={styles.spacer} />

      <TouchableOpacity
        style={styles.agreementWrapper}
        {...makeTestIDProps(E2E_ID.onboarding.setPasswordAgreement)}
        onPress={() => {
          formik.setFieldValue('checked', !formik.values.checked, true);
        }}>
        <View style={styles.agreementCheckbox}>
          <CheckBoxRect checked={formik.values.checked} />
        </View>
        <Text style={styles.agreementText}>
          {t('page.createPassword.agreeToTerms')}{' '}
          <Text
            style={styles.userAgreementTouchText}
            suppressHighlighting
            onPress={evt => {
              evt.stopPropagation();
              viewTermsOfUse();
            }}>
            {t('page.createPassword.termOfUse')}
          </Text>{' '}
          {t('page.createPassword.and')}{' '}
          <Text
            style={styles.userAgreementTouchText}
            suppressHighlighting
            onPress={evt => {
              evt.stopPropagation();
              viewPrivacyPolicy();
            }}>
            {t('page.createPassword.PrivacyPolicy')}
          </Text>
        </Text>
      </TouchableOpacity>

      <Button
        disabled={shouldDisabled}
        loading={loading}
        containerStyle={styles.btnContainer}
        type="primary"
        title={
          isBiometricMode
            ? t('page.createPassword.setWallet')
            : submitButtonTitle || t('global.Done')
        }
        icon={
          isBiometricMode ? (
            isFaceID ? (
              <RcIconKeychainFaceIdCC
                color={colors2024['neutral-InvertHighlight']}
                width={22}
                height={22}
              />
            ) : (
              <RcIconKeychainFingerprintCC
                color={colors2024['neutral-InvertHighlight']}
                width={22}
                height={22}
              />
            )
          ) : undefined
        }
        {...makeTestIDProps(E2E_ID.onboarding.setPasswordSubmit)}
        onPress={handlePress}
      />
    </View>
  );
};

const getStyle = createGetStyles2024(({ colors2024 }) => ({
  container: {
    width: '100%',
    flex: 1,
  },
  topTipText: {
    color: colors2024['neutral-secondary'],
    fontWeight: '500',
    fontSize: 18,
    marginBottom: 24,
    textAlign: 'center',
    fontFamily: 'SF Pro Rounded',
  },
  inputHorizontalGroup: {
    width: '100%',
    flexDirection: 'column',
  },
  inputStyle: {
    borderWidth: 0,
    backgroundColor: colors2024['neutral-bg-2'],
    borderRadius: 12,
  },
  paddingLeft: {
    paddingLeft: 16,
  },
  absoluteLeft: {
    left: 16,
  },
  labelText: {
    width: '50%',
    fontSize: 14,
    fontWeight: '400',
    fontFamily: 'SF Pro Rounded',
    color: colors2024['neutral-title-1'],
  },
  valueView: {
    width: '50%',
    flexDirection: 'row',
    justifyContent: 'flex-end',
  },
  switchContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 24,
    paddingHorizontal: 8,
  },
  switchContainerDisabled: {
    opacity: 0.45,
  },
  agreementWrapper: {
    marginTop: 24,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 24,
  },
  agreementCheckbox: {
    marginRight: 6,
  },
  agreementText: {
    fontSize: 14,
    lineHeight: 18,
    fontWeight: '400',
    fontFamily: 'SF Pro Rounded',
    color: colors2024['neutral-secondary'],
  },
  userAgreementTouchText: {
    fontSize: 14,
    lineHeight: 18,
    fontWeight: '400',
    fontFamily: 'SF Pro Rounded',
    color: colors2024['brand-default'],
  },
  spacer: {
    flex: 1,
  },
  btnContainer: {
    width: '100%',
    marginTop: 16,
    marginBottom: 48,
  },
}));

export default PasswordForm;
