import NormalScreenContainer from '@/components/ScreenContainer/NormalScreenContainer';
import React from 'react';
import { View, Pressable, Image } from 'react-native';
import { useTranslation } from 'react-i18next';
import { useTheme2024 } from '@/hooks/theme';
import { createGetStyles2024 } from '@/utils/styles';
import { IS_IOS } from '@/core/native/utils';
import { Text } from '@/components/Typography';
import { useRoute, useNavigation } from '@react-navigation/native';
import type { RouteProp } from '@react-navigation/native';

import RcIconBackupManual from '@/assets2024/icons/backup/manual.svg';

const IconIcloudSrc = require('@/assets2024/icons/common/IconIcloud.png');
const IconGoogleDriveSrc = require('@/assets2024/icons/common/IconGoogleDrive.png');
import {
  createGlobalBottomSheetModal2024,
  removeGlobalBottomSheetModal2024,
} from '@/components2024/GlobalBottomSheetModal';
import { MODAL_NAMES } from '@/components2024/GlobalBottomSheetModal/types';
import { AuthenticationModal2024 } from '@/components/AuthenticationModal/AuthenticationModal2024';
import { apiMnemonic } from '@/core/apis';
import { KEYRING_TYPE } from '@rabby-wallet/keyring-utils';
import { useEnterPassphraseModal } from '@/hooks/useEnterPassphraseModal';
import { clearAccountBackupReminder } from '@/hooks/account';
import type { RootStackParamsList } from '@/navigation-type';
import type { RootNames } from '@/constant/layout';
import { checkCloudBackupExists } from '@/core/utils/cloudBackup';
import { apisKeychain, apisLock } from '@/core/apis';
import { RequestGenericPurpose } from '@/core/apis/keychain';
import {
  getPasswordIsAutoGeneratedSnapshot,
  setPasswordIsAutoGenerated,
} from '@/core/serviceApi/preference';
import { storeApisBiometrics, useBiometricsComputed } from '@/hooks/biometrics';
import SetPasswordBottomSheet from '@/screens/ManagePassword/components/SetPasswordBottomSheet';
import { useCloudBackup } from '@/components/SeedPhraseBackupToCloud2024/useCloudBackup';
import { toast } from '@/components2024/Toast';

type BackupScreenRouteProp = RouteProp<
  RootStackParamsList,
  typeof RootNames.Backup
>;

function Backup(): JSX.Element {
  const { t } = useTranslation();
  const { styles, colors2024 } = useTheme2024({ getStyle });
  const route = useRoute<BackupScreenRouteProp>();
  const navigation = useNavigation();
  const bioComputed = useBiometricsComputed();

  const { address, type, brandName } = route.params || {};
  const invokeEnterPassphrase = useEnterPassphraseModal('address');

  const [hasCloudBackup, setHasCloudBackup] = React.useState(false);
  const [showSetPasswordSheet, setShowSetPasswordSheet] = React.useState(false);
  const [setPasswordLoading, setSetPasswordLoading] = React.useState(false);
  const autoGenPasswordForBackupRef = React.useRef('');

  React.useEffect(() => {
    if (!address) return;
    if (getPasswordIsAutoGeneratedSnapshot()) return;

    const checkCloudBackup = async () => {
      try {
        const exists = await checkCloudBackupExists(address);
        setHasCloudBackup(exists);
      } catch (error) {
        console.error('Failed to check cloud backup status:', error);
      }
    };

    checkCloudBackup();
  }, [address]);

  const handleBackupComplete = React.useCallback(() => {
    if (address && type && brandName) {
      clearAccountBackupReminder({
        address,
        type: type as KEYRING_TYPE,
        brandName,
      });
    }
    navigation.goBack();
  }, [address, type, brandName, navigation]);

  const { handleUpload } = useCloudBackup({ onDone: handleBackupComplete });

  const handleSetPasswordAndUpload = React.useCallback(
    async (newPassword: string) => {
      setSetPasswordLoading(true);
      try {
        if (!address) return;

        const autoGenPassword = autoGenPasswordForBackupRef.current;
        const seedPhraseData = await apiMnemonic.getMnemonics(
          autoGenPassword,
          address,
        );

        const result = await apisLock.updateWalletPassword(
          autoGenPassword,
          newPassword,
        );
        if (result.error) {
          throw new Error(result.error);
        }
        await setPasswordIsAutoGenerated(false);
        await storeApisBiometrics.toggleBiometrics(true, {
          validatedPassword: newPassword,
        });
        await handleUpload(newPassword, seedPhraseData);
        setShowSetPasswordSheet(false);
      } catch {
        toast.show(t('page.addressDetail.backupFailed'));
      } finally {
        setSetPasswordLoading(false);
      }
    },
    [address, handleUpload, t],
  );

  // Get auth modal labels based on actual/current auth type
  const getAuthModalLabels = React.useCallback(
    (authType: 'password' | 'biometrics' | 'none') => {
      if (authType === 'biometrics') {
        if (bioComputed.isFaceID) {
          return {
            title: t('page.addressDetail.verify-face-id'),
            description: t('page.addressDetail.verify-face-id-before-backup'),
          };
        }
        return {
          title: t('page.addressDetail.verify-fingerprint'),
          description: t('page.addressDetail.verify-fingerprint-before-backup'),
        };
      }
      return {
        title: t('page.addressDetail.verify-password'),
        description: t('page.addressDetail.verify-password-before-backup'),
      };
    },
    [bioComputed.isFaceID, t],
  );

  const handleCloudBackupWithAutoGenPassword = React.useCallback(async () => {
    try {
      await apisKeychain.requestGenericPassword({
        purpose: RequestGenericPurpose.DECRYPT_PWD,
        onPlainPassword(password) {
          autoGenPasswordForBackupRef.current = password;
        },
      });
    } catch {
      // User cancelled biometrics — abort
      return;
    }

    if (!address) return;

    setShowSetPasswordSheet(true);
  }, [address]);

  const handleBackupToCloud = React.useCallback(() => {
    if (getPasswordIsAutoGeneratedSnapshot()) {
      handleCloudBackupWithAutoGenPassword();
      return;
    }

    // For cloud backup from AddressDetail, we need to authenticate first to get
    // the seed phrase, then pass it to the cloud backup modal.
    let seedPhraseData = '';

    AuthenticationModal2024.show({
      confirmText: t('page.addressDetail.verify-and-backup'),
      title: authType => getAuthModalLabels(authType).title,
      description: authType => getAuthModalLabels(authType).description,
      hideCancelButton: true,
      validationHandler: async (password: string) => {
        if (!address) return;
        seedPhraseData = await apiMnemonic.getMnemonics(password, address);

        if (type === KEYRING_TYPE.HdKeyring) {
          await invokeEnterPassphrase(address);
        }
      },
      onFinished(ctx) {
        if (ctx.hasSetupCustomPassword && !seedPhraseData) {
          return;
        }

        const id = createGlobalBottomSheetModal2024({
          name: MODAL_NAMES.SEED_PHRASE_BACKUP_TO_CLOUD,
          bottomSheetModalProps: {
            enableContentPanningGesture: true,
            enablePanDownToClose: true,
          },
          // Pass seed phrase for existing user backup flow
          seedPhraseData,
          skipKeyringCreation: true,
          onDone: () => {
            removeGlobalBottomSheetModal2024(id);
            handleBackupComplete();
          },
        });
      },
    });
  }, [
    address,
    type,
    t,
    invokeEnterPassphrase,
    handleBackupComplete,
    getAuthModalLabels,
    handleCloudBackupWithAutoGenPassword,
  ]);

  const handleBackupToPaper = React.useCallback(() => {
    let seedPhraseData = '';

    AuthenticationModal2024.show({
      confirmText: t('page.addressDetail.verify-and-backup'),
      title: authType => getAuthModalLabels(authType).title,
      description: authType => getAuthModalLabels(authType).description,
      hideCancelButton: true,
      validationHandler: async (password: string) => {
        if (!address) return;
        seedPhraseData = await apiMnemonic.getMnemonics(password, address);

        if (type === KEYRING_TYPE.HdKeyring) {
          await invokeEnterPassphrase(address);
        }
      },
      onFinished(ctx) {
        if (ctx.hasSetupCustomPassword && !seedPhraseData) {
          return;
        }

        const id = createGlobalBottomSheetModal2024({
          name: MODAL_NAMES.SEED_PHRASE_MANUAL_BACKUP,
          bottomSheetModalProps: {
            enableContentPanningGesture: false,
            enablePanDownToClose: true,
          },
          preventScreenshotOnModalOpen: false,
          readMode: true,
          seedPhraseData,
          onDone: () => {
            removeGlobalBottomSheetModal2024(id);
            handleBackupComplete();
          },
        });
      },
    });
  }, [
    address,
    type,
    t,
    invokeEnterPassphrase,
    handleBackupComplete,
    getAuthModalLabels,
  ]);

  return (
    <NormalScreenContainer
      overwriteStyle={{
        backgroundColor: colors2024['neutral-bg-0'],
      }}>
      <View style={styles.container}>
        {/* Cloud Backup Card */}
        <Pressable
          style={styles.card}
          onPress={handleBackupToCloud}
          android_ripple={{ color: colors2024['neutral-line'] }}>
          <View style={styles.cardContent}>
            <View style={styles.iconRow}>
              <Image
                source={IS_IOS ? IconIcloudSrc : IconGoogleDriveSrc}
                style={styles.cloudIcon}
              />
              <Text style={styles.cardTitle}>
                {IS_IOS
                  ? t('page.newAddress.seedPhrase.icloudBackup')
                  : t('page.newAddress.seedPhrase.googleDriveBackup')}
              </Text>
            </View>
            {hasCloudBackup ? (
              <View style={styles.doneBadge}>
                <Text style={styles.doneBadgeText}>
                  {t('page.newAddress.Done')}
                </Text>
              </View>
            ) : (
              <View style={styles.quickBadge}>
                <Text style={styles.quickBadgeText}>
                  {t('page.newAddress.Quick')}
                </Text>
              </View>
            )}
          </View>
        </Pressable>

        {/* Manual Backup Card */}
        <Pressable
          style={styles.card}
          onPress={handleBackupToPaper}
          android_ripple={{ color: colors2024['neutral-line'] }}>
          <View style={styles.cardContent}>
            <View style={styles.iconRow}>
              <RcIconBackupManual width={40} height={40} />
              <Text style={styles.cardTitle}>
                {t('page.newAddress.seedPhrase.manuallyBackup')}
              </Text>
            </View>
          </View>
        </Pressable>
      </View>
      <SetPasswordBottomSheet
        visible={showSetPasswordSheet}
        loading={setPasswordLoading}
        showBiometricIcon
        onConfirm={handleSetPasswordAndUpload}
        onClose={() => setShowSetPasswordSheet(false)}
      />
    </NormalScreenContainer>
  );
}

const getStyle = createGetStyles2024(({ colors2024, isLight }) => ({
  container: {
    flex: 1,
    paddingHorizontal: 24,
    paddingTop: 16,
  },
  card: {
    backgroundColor: isLight
      ? colors2024['neutral-bg-1']
      : colors2024['neutral-bg-2'],
    borderRadius: 20,
    marginBottom: 12,
    padding: 20,
    shadowColor: colors2024['neutral-title-1'],
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.05,
    shadowRadius: 20,
  },
  cardContent: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  iconRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  cardTitle: {
    fontSize: 18,
    lineHeight: 22,
    color: colors2024['neutral-title-1'],
    fontWeight: '700',
    fontFamily: 'SF Pro Rounded',
  },
  cloudIcon: {
    width: 40,
    height: 40,
    borderRadius: 14,
  },
  quickBadge: {
    backgroundColor: colors2024['brand-light-1'],
    paddingHorizontal: 6,
    paddingVertical: 4,
    borderRadius: 8,
  },
  quickBadgeText: {
    fontSize: 12,
    lineHeight: 16,
    color: colors2024['brand-default'],
    fontWeight: '700',
    fontFamily: 'SF Pro Rounded',
  },
  doneBadge: {
    backgroundColor: colors2024['green-light-1'],
    paddingHorizontal: 6,
    paddingVertical: 4,
    borderRadius: 8,
  },
  doneBadgeText: {
    fontSize: 12,
    lineHeight: 16,
    color: colors2024['green-default'],
    fontWeight: '700',
    fontFamily: 'SF Pro Rounded',
  },
}));

export default Backup;
