compressionLevel: mixed

enableGlobalCache: false

enableScripts: false

enableTelemetry: 0

logFilters:
  - code: YN0004
    level: discard

nodeLinker: node-modules

npmMinimalAgeGate: 15d

npmPreapprovedPackages:
  - '@rabby-wallet/*'
  - '@debank/*'

yarnPath: .yarn/releases/yarn-4.12.0.cjs

# npmRegistryServer: https://registry.npmmirror.com

# ⚠️ !!! fill you token on ~/.yarnrc.yml, not here!
# npmAuthToken:
