/* eslint-disable */
// AUTO-GENERATED EAGER IMPLEMENTATION FROM ./homeRootNavigator.lazy.ts.
// DO NOT EDIT THIS FILE DIRECTLY.

export { HomeScreenNavigator } from '@/screens/Navigators/rootNavigator';
