/* eslint-disable */
// AUTO-GENERATED FROM ./rootNavigatorScreens.lazy.ts BY `yarn workspace rabby-mobile loadables:generate`.
// DO NOT EDIT THIS FILE DIRECTLY.

export * from './rootNavigatorScreens.lazy';
