import React, { type Ref, useImperativeHandle, useState, useRef } from 'react';
import { Alert } from 'react-native';
import { AppSwitch2024 } from '@/components/customized/Switch2024';
import type { SwitchToggleType } from '@/components';
import { useBiometrics } from '@/hooks/biometrics';
import { useWalletPasswordInfo } from '@/screens/ManagePassword/useManagePassword';
import { AuthenticationModal2024 as AuthenticationModal } from '@/components/AuthenticationModal/AuthenticationModal2024';
import { useTranslation } from 'react-i18next';
import { apisKeychain, apisLock } from '@/core/apis';
import { RequestGenericPurpose } from '@/core/apis/keychain';
import {
  getPasswordIsAutoGeneratedSnapshot,
  setPasswordIsAutoGenerated,
} from '@/core/serviceApi/preference';
import SetPasswordBottomSheet from '@/screens/ManagePassword/components/SetPasswordBottomSheet';

function useToggleBiometricsEnabled() {
  const { computed, toggleBiometrics } = useBiometrics();
  const { t } = useTranslation();
  const [sheetVisible, setSheetVisible] = useState(false);
  const [sheetLoading, setSheetLoading] = useState(false);
  const autoGenPasswordRef = useRef('');

  const requestToggleBiometricsEnabled = React.useCallback(
    async (
      nextEnabled: boolean,
      onToggleSuccess?: (enabled: boolean) => void | Promise<void>,
    ) => {
      // When turning OFF and password is auto-generated:
      // verify biometrics → show password setup → update password → turn off
      if (!nextEnabled && getPasswordIsAutoGeneratedSnapshot()) {
        try {
          await apisKeychain.requestGenericPassword({
            purpose: RequestGenericPurpose.DECRYPT_PWD,
            onPlainPassword(password) {
              autoGenPasswordRef.current = password;
            },
          });
        } catch (_error) {
          // User cancelled or biometrics failed — abort, switch stays on
          return;
        }

        setSheetVisible(true);
        return;
      }

      // Non-auto-gen disable: system confirm popup
      if (!nextEnabled) {
        Alert.alert(
          t('component.AuthenticationModals.biometrics.disable', {
            bioType: computed.systemAuthTypeLabel,
          }),
          undefined,
          [
            { text: t('page.unlock.biometrics.enableBiometricAlert.no') },
            {
              text: t('page.unlock.biometrics.enableBiometricAlert.yes'),
              onPress: async () => {
                const changed = await toggleBiometrics(false, {});
                if (changed) {
                  await onToggleSuccess?.(false);
                }
              },
            },
          ],
        );
        return;
      }

      // Enabling biometrics: needs password verification
      AuthenticationModal.show({
        confirmText: t('global.confirm'),
        cancelText: t('global.cancel'),
        title: t('component.AuthenticationModals.biometrics.enable', {
          bioType: computed.systemAuthTypeLabel,
        }),
        authType: ['password'],
        async onFinished({ getValidatedPassword }) {
          const changed = await toggleBiometrics(true, {
            validatedPassword: getValidatedPassword(),
          });
          if (changed) {
            await onToggleSuccess?.(true);
          }
        },
      });
    },
    [toggleBiometrics, computed.systemAuthTypeLabel, t],
  );

  const handleSheetConfirm = React.useCallback(
    async (newPassword: string) => {
      setSheetLoading(true);
      try {
        // 1. Update wallet password from auto-gen to user-chosen
        const result = await apisLock.updateWalletPassword(
          autoGenPasswordRef.current,
          newPassword,
        );
        if (result.error) {
          throw new Error(result.error);
        }

        // 2. Clear the auto-gen flag
        await setPasswordIsAutoGenerated(false);

        // 3. Turn off biometrics
        await toggleBiometrics(false, {});
      } catch (_error) {
        // Password update failed — stay on sheet
        return;
      } finally {
        setSheetLoading(false);
      }

      setSheetVisible(false);
    },
    [toggleBiometrics],
  );

  return {
    isBiometricsEnabled: computed.isBiometricsEnabled,
    couldSetupBiometrics: computed.couldSetupBiometrics,
    couldSetupSystemAuth: computed.couldSetupSystemAuth,
    isUsingDevicePasscodeForSettings: computed.isUsingDevicePasscodeForSettings,
    requestToggleBiometricsEnabled,
    sheetVisible,
    sheetLoading,
    handleSheetConfirm,
    setSheetVisible,
  };
}

export const SwitchBiometricsAuthentication = ({
  ref,
  onToggleSuccess,
  onUnavailablePress,
  ...props
}: React.ComponentProps<typeof AppSwitch2024> & {
  onToggleSuccess?: (enabled: boolean) => void | Promise<void>;
  onUnavailablePress?: () => void;
  ref?: Ref<SwitchToggleType>;
}) => {
  const {
    isBiometricsEnabled,
    couldSetupBiometrics,
    requestToggleBiometricsEnabled,
    sheetVisible,
    sheetLoading,
    handleSheetConfirm,
    setSheetVisible,
    isUsingDevicePasscodeForSettings,
  } = useToggleBiometricsEnabled();

  useImperativeHandle(ref, () => ({
    toggle: async (enabled?: boolean) => {
      await requestToggleBiometricsEnabled(
        enabled ?? (!isBiometricsEnabled && !isUsingDevicePasscodeForSettings),
        onToggleSuccess,
      );
    },
  }));

  const { hasSetupCustomPassword } = useWalletPasswordInfo();

  const switchValue = couldSetupBiometrics
    ? !!isBiometricsEnabled
    : isUsingDevicePasscodeForSettings;
  const isBiometricsUnavailableForSetup = !couldSetupBiometrics && !switchValue;
  const switchDisabled =
    !hasSetupCustomPassword || isBiometricsUnavailableForSetup;

  return (
    <>
      <AppSwitch2024
        {...props}
        circleSize={20}
        disabled={switchDisabled}
        value={switchValue}
        changeValueImmediately={false}
        onPress={evt => {
          if (switchDisabled && isBiometricsUnavailableForSetup) {
            evt.stopPropagation?.();
            onUnavailablePress?.();
          }
        }}
        onValueChange={enabled => {
          requestToggleBiometricsEnabled(enabled, onToggleSuccess);
        }}
      />
      <SetPasswordBottomSheet
        visible={sheetVisible}
        loading={sheetLoading}
        onConfirm={handleSheetConfirm}
        onClose={() => setSheetVisible(false)}
      />
    </>
  );
};
