import {
  getNextUnlockAuthenticationState,
  shouldKeepStoredCredentialIconWhenSystemAuthUnavailable,
  shouldShowSystemAuthUnavailableTipForUnlock,
  shouldUsePasswordUnlockMode,
} from './authState';

describe('Unlock auth state', () => {
  it('returns to system auth when passcode-capable credentials become available after async biometrics fetch', () => {
    expect(
      getNextUnlockAuthenticationState({
        usingBiometrics: false,
        isBiometricsEnabled: true,
        passwordIsAutoGenerated: false,
        couldSetupSystemAuth: true,
        userSelectedPasswordForSession: false,
        previousCanUseStoredCredential: false,
      }),
    ).toEqual({
      usingBiometrics: true,
      nextPreviousCanUseStoredCredential: true,
      shouldTriggerAutoUnlock: true,
    });
  });

  it('keeps password mode when the user already selected password for this unlock session', () => {
    expect(
      getNextUnlockAuthenticationState({
        usingBiometrics: false,
        isBiometricsEnabled: true,
        passwordIsAutoGenerated: false,
        couldSetupSystemAuth: true,
        userSelectedPasswordForSession: true,
        previousCanUseStoredCredential: false,
      }),
    ).toEqual({
      usingBiometrics: false,
      nextPreviousCanUseStoredCredential: true,
      shouldTriggerAutoUnlock: false,
    });
  });

  it('switches to password mode when no stored credential unlock path is available', () => {
    expect(
      getNextUnlockAuthenticationState({
        usingBiometrics: true,
        isBiometricsEnabled: false,
        passwordIsAutoGenerated: false,
        couldSetupSystemAuth: false,
        userSelectedPasswordForSession: false,
        previousCanUseStoredCredential: true,
      }),
    ).toEqual({
      usingBiometrics: false,
      nextPreviousCanUseStoredCredential: false,
      shouldTriggerAutoUnlock: false,
    });
  });

  it('keeps the stored credential icon when autogenerated password has no system auth path', () => {
    expect(
      getNextUnlockAuthenticationState({
        usingBiometrics: false,
        isBiometricsEnabled: false,
        passwordIsAutoGenerated: true,
        couldSetupSystemAuth: false,
        userSelectedPasswordForSession: true,
        previousCanUseStoredCredential: true,
      }),
    ).toEqual({
      usingBiometrics: true,
      nextPreviousCanUseStoredCredential: true,
      shouldTriggerAutoUnlock: false,
    });

    expect(
      shouldKeepStoredCredentialIconWhenSystemAuthUnavailable({
        isBiometricsEnabled: false,
        passwordIsAutoGenerated: true,
        couldSetupSystemAuth: false,
      }),
    ).toBe(true);

    expect(
      shouldShowSystemAuthUnavailableTipForUnlock({
        biometricsReady: false,
        isBiometricsEnabled: false,
        passwordIsAutoGenerated: true,
        couldSetupSystemAuth: false,
      }),
    ).toBe(true);

    expect(
      shouldUsePasswordUnlockMode({
        usingBiometrics: false,
        isBiometricsEnabled: false,
        passwordIsAutoGenerated: true,
        couldSetupSystemAuth: false,
      }),
    ).toBe(false);
  });

  it('does not keep the stored credential icon when app password or system auth is available', () => {
    expect(
      shouldKeepStoredCredentialIconWhenSystemAuthUnavailable({
        isBiometricsEnabled: false,
        passwordIsAutoGenerated: false,
        couldSetupSystemAuth: false,
      }),
    ).toBe(false);

    expect(
      shouldKeepStoredCredentialIconWhenSystemAuthUnavailable({
        isBiometricsEnabled: false,
        passwordIsAutoGenerated: true,
        couldSetupSystemAuth: true,
      }),
    ).toBe(false);

    expect(
      shouldUsePasswordUnlockMode({
        usingBiometrics: false,
        isBiometricsEnabled: false,
        passwordIsAutoGenerated: false,
        couldSetupSystemAuth: false,
      }),
    ).toBe(true);

    expect(
      shouldShowSystemAuthUnavailableTipForUnlock({
        biometricsReady: true,
        isBiometricsEnabled: false,
        passwordIsAutoGenerated: true,
        couldSetupSystemAuth: false,
      }),
    ).toBe(false);
  });
});
