describe('utils/walletUnlock', () => {
  const setup = async ({
    isUnlocked = false,
    passwordIsAutoGenerated = false,
    isAuthenticatedByBiometrics = true,
    supportedBiometryType = 'Fingerprint' as string | null,
    authType = 1,
    passcodeAuthAvailable = false,
    rejectKeychainRequest = false,
    isAndroid = true,
  } = {}) => {
    jest.resetModules();

    jest.spyOn(console, 'error').mockImplementation(() => {});

    const mockHideUnlockingToast = jest.fn();
    const mockToastUnlocking = jest.fn(() => mockHideUnlockingToast);
    const mockVerifyPasswordOrUnlock = jest.fn(async () => undefined);
    const mockRequestGenericPassword = jest.fn(async options => {
      if (rejectKeychainRequest) {
        throw new Error('Keychain unavailable');
      }

      await options.onPlainPassword?.('plain-password');
      return { actionSuccess: true };
    });
    const mockGetSupportedBiometryType = jest.fn(
      async () => supportedBiometryType,
    );
    const mockIsPasscodeAuthAvailable = jest.fn(
      async () => passcodeAuthAvailable,
    );
    const mockShowAuthenticationModal = jest.fn(async config => {
      await config.validationHandler?.('custom-password');
      config.onFinished?.();
      return { hideModal: jest.fn() };
    });

    jest.doMock('@/core/apis/keychain', () => ({
      RequestGenericPurpose: {
        DECRYPT_PWD: 11,
      },
      KEYCHAIN_AUTH_TYPES: {
        BIOMETRICS: 1,
        BIOMETRICS_OR_PASSCODE: 4,
      },
      isAuthenticatedByBiometrics: jest.fn(() => isAuthenticatedByBiometrics),
      getAuthenticationType: jest.fn(() => authType),
      getSupportedBiometryType: mockGetSupportedBiometryType,
      isPasscodeAuthAvailable: mockIsPasscodeAuthAvailable,
      requestGenericPassword: mockRequestGenericPassword,
    }));

    jest.doMock('@/core/native/utils', () => ({
      IS_ANDROID: isAndroid,
      IS_IOS: !isAndroid,
    }));

    jest.doMock('@/core/apis/lock', () => ({
      isUnlocked: jest.fn(() => isUnlocked),
      ensureKeyringRuntimeReady: jest.fn(async () => undefined),
      verifyPasswordOrUnlock: mockVerifyPasswordOrUnlock,
    }));

    jest.doMock('@/core/serviceApi/preference', () => ({
      getPasswordIsAutoGeneratedSnapshot: jest.fn(
        () => passwordIsAutoGenerated,
      ),
    }));

    jest.doMock('@/utils/toastUnlocking', () => ({
      toastUnlocking: mockToastUnlocking,
    }));

    jest.doMock('@/utils/walletUnlockGuard', () => ({
      setWalletUnlockRequester: jest.fn(),
    }));

    jest.doMock(
      '@/components/AuthenticationModal/AuthenticationModal2024',
      () => ({
        AuthenticationModal2024: {
          show: mockShowAuthenticationModal,
        },
      }),
    );

    const walletUnlock =
      require('./walletUnlock') as typeof import('./walletUnlock');

    return {
      walletUnlock,
      mockVerifyPasswordOrUnlock,
      mockRequestGenericPassword,
      mockGetSupportedBiometryType,
      mockIsPasscodeAuthAvailable,
      mockShowAuthenticationModal,
      mockToastUnlocking,
      mockHideUnlockingToast,
    };
  };

  afterEach(() => {
    jest.restoreAllMocks();
  });

  it('uses an error message instead of the i18n key for cancellation', async () => {
    const { walletUnlock } = await setup();

    const error = new walletUnlock.WalletUnlockCancelledError();

    expect(error.name).toBe('WalletUnlockCancelledError');
    expect(error.message).toBe('Wallet unlock cancelled');
    expect(error.message).not.toBe('wallet.unlock.cancelled');
    expect(walletUnlock.isWalletUnlockCancelled(error)).toBe(true);
    expect(
      walletUnlock.isWalletUnlockCancelled(
        new Error('wallet.unlock.cancelled'),
      ),
    ).toBe(false);
  });

  it('uses system credential unlock for autogenerated passwords even when biometrics are disabled', async () => {
    const {
      walletUnlock,
      mockVerifyPasswordOrUnlock,
      mockRequestGenericPassword,
      mockGetSupportedBiometryType,
      mockShowAuthenticationModal,
      mockToastUnlocking,
      mockHideUnlockingToast,
    } = await setup({
      passwordIsAutoGenerated: true,
      isAuthenticatedByBiometrics: false,
      supportedBiometryType: null,
    });

    await walletUnlock.ensureWalletUnlocked();

    expect(mockGetSupportedBiometryType).not.toHaveBeenCalled();
    expect(mockRequestGenericPassword).toHaveBeenCalledWith(
      expect.objectContaining({
        purpose: 11,
      }),
    );
    expect(mockVerifyPasswordOrUnlock).toHaveBeenCalledWith('plain-password');
    expect(mockShowAuthenticationModal).not.toHaveBeenCalled();
    expect(mockToastUnlocking).toHaveBeenCalledTimes(1);
    expect(mockHideUnlockingToast).toHaveBeenCalledTimes(1);
  });

  it('falls back to the custom password modal when biometrics are gone even if Android passcode is available', async () => {
    const {
      walletUnlock,
      mockVerifyPasswordOrUnlock,
      mockRequestGenericPassword,
      mockGetSupportedBiometryType,
      mockIsPasscodeAuthAvailable,
      mockShowAuthenticationModal,
    } = await setup({
      supportedBiometryType: null,
      authType: 4,
      passcodeAuthAvailable: true,
    });

    await walletUnlock.ensureWalletUnlocked();

    expect(mockGetSupportedBiometryType).toHaveBeenCalled();
    expect(mockIsPasscodeAuthAvailable).not.toHaveBeenCalled();
    expect(mockRequestGenericPassword).not.toHaveBeenCalled();
    expect(mockShowAuthenticationModal).toHaveBeenCalledWith(
      expect.objectContaining({
        authType: ['password'],
      }),
    );
    expect(mockVerifyPasswordOrUnlock).toHaveBeenCalledWith('custom-password');
  });

  it('falls back to the custom password modal for old Android biometrics auth settings when enrollment is gone', async () => {
    const {
      walletUnlock,
      mockVerifyPasswordOrUnlock,
      mockRequestGenericPassword,
      mockGetSupportedBiometryType,
      mockIsPasscodeAuthAvailable,
      mockShowAuthenticationModal,
    } = await setup({
      supportedBiometryType: null,
      authType: 1,
      passcodeAuthAvailable: true,
      isAndroid: true,
    });

    await walletUnlock.ensureWalletUnlocked();

    expect(mockGetSupportedBiometryType).toHaveBeenCalled();
    expect(mockIsPasscodeAuthAvailable).not.toHaveBeenCalled();
    expect(mockRequestGenericPassword).not.toHaveBeenCalled();
    expect(mockShowAuthenticationModal).toHaveBeenCalledWith(
      expect.objectContaining({
        authType: ['password'],
      }),
    );
    expect(mockVerifyPasswordOrUnlock).toHaveBeenCalledWith('custom-password');
  });

  it('shows unlocking toast for biometric post-unlock', async () => {
    const {
      walletUnlock,
      mockVerifyPasswordOrUnlock,
      mockRequestGenericPassword,
      mockToastUnlocking,
      mockHideUnlockingToast,
      mockShowAuthenticationModal,
    } = await setup();

    await walletUnlock.ensureWalletUnlocked();

    expect(mockRequestGenericPassword.mock.invocationCallOrder[0]).toBeLessThan(
      mockToastUnlocking.mock.invocationCallOrder[0],
    );
    expect(mockToastUnlocking.mock.invocationCallOrder[0]).toBeLessThan(
      mockVerifyPasswordOrUnlock.mock.invocationCallOrder[0],
    );
    expect(mockToastUnlocking).toHaveBeenCalledTimes(1);
    expect(mockHideUnlockingToast).toHaveBeenCalledTimes(1);
    expect(mockShowAuthenticationModal).not.toHaveBeenCalled();
  });

  it('shows unlocking toast for non-Android biometric post-unlock', async () => {
    const { walletUnlock, mockToastUnlocking, mockHideUnlockingToast } =
      await setup({ isAndroid: false });

    await walletUnlock.ensureWalletUnlocked();

    expect(mockToastUnlocking).toHaveBeenCalledTimes(1);
    expect(mockHideUnlockingToast).toHaveBeenCalledTimes(1);
  });

  it('shows unlocking toast for FaceID-style biometry', async () => {
    const { walletUnlock, mockToastUnlocking, mockHideUnlockingToast } =
      await setup({ supportedBiometryType: 'FaceID' });

    await walletUnlock.ensureWalletUnlocked();

    expect(mockToastUnlocking).toHaveBeenCalledTimes(1);
    expect(mockHideUnlockingToast).toHaveBeenCalledTimes(1);
  });

  it('does not fall back to password modal when autogenerated-password keychain unlock fails', async () => {
    const {
      walletUnlock,
      mockShowAuthenticationModal,
      mockToastUnlocking,
      mockHideUnlockingToast,
    } = await setup({
      passwordIsAutoGenerated: true,
      rejectKeychainRequest: true,
    });

    await expect(walletUnlock.ensureWalletUnlocked()).rejects.toMatchObject({
      name: 'WalletUnlockCancelledError',
    });
    expect(mockShowAuthenticationModal).not.toHaveBeenCalled();
    expect(mockToastUnlocking).not.toHaveBeenCalled();
    expect(mockHideUnlockingToast).not.toHaveBeenCalled();
  });
});
