import type {
  ChainGas,
  GasCache,
  IPinAddress,
  PreferenceService,
  PreferenceStore,
  Token,
  TokenDisplayMode,
} from '@/core/startupServices/preference';
import { getRegisteredService } from '@/core/services/serviceRegistry';
import { createDeferredServiceApi } from './createDeferredServiceApi';

export type PreferenceServiceApiContract = PreferenceService;
export const preferenceServiceApi = createDeferredServiceApi<
  'preferenceService',
  PreferenceServiceApiContract
>('preferenceService');

export function getFallbackAccountSnapshot() {
  return (
    getRegisteredService('preferenceService')?.getFallbackAccount() || null
  );
}

export function getIsShowTestnetSnapshot() {
  return getRegisteredService('preferenceService')?.getIsShowTestnet() || false;
}

export function getPasswordIsAutoGeneratedSnapshot() {
  return (
    getRegisteredService('preferenceService')?.store.passwordIsAutoGenerated ||
    false
  );
}

export function getWatchlistSkipSnapshot() {
  return getRegisteredService('preferenceService')?.getWatchlistSkip() || false;
}

export function getTokenDisplayModeSnapshot(): TokenDisplayMode {
  return (
    getRegisteredService('preferenceService')?.getTokenDisplayMode() ||
    'byAddress'
  );
}

export async function setWatchlistSkip(value: boolean) {
  await preferenceServiceApi.setWatchlistSkip(value);
}

export async function setHasShowAsterPopup(value: boolean) {
  await preferenceServiceApi.setHasShowAsterPopup(value);
}

export async function setTokenDisplayMode(mode: TokenDisplayMode) {
  await preferenceServiceApi.setTokenDisplayMode(mode);
}

export async function toggleAllowNotifyAccountsChanged(allowed: boolean) {
  await preferenceServiceApi.toggleAllowNotifyAccountsChanged(allowed);
}

export function toggleAllowNotifyAccountsChangedSync(allowed: boolean) {
  const service = getRegisteredService('preferenceService');
  if (!service) {
    throw new Error('preferenceService is not ready');
  }
  service.toggleAllowNotifyAccountsChanged(allowed);
}

export function getPreferenceSnapshot(): PreferenceStore | undefined;
export function getPreferenceSnapshot<K extends keyof PreferenceStore>(
  key: K,
): PreferenceStore[K] | undefined;
export function getPreferenceSnapshot(key?: keyof PreferenceStore) {
  const service = getRegisteredService('preferenceService');
  return key ? service?.getPreference(key) : service?.getPreference();
}

export function initCurrentAccountSync() {
  const service = getRegisteredService('preferenceService');
  if (!service) {
    throw new Error('preferenceService is not ready');
  }
  service.initCurrentAccount();
}

export async function getLastTimeGasSelection(chainId: keyof GasCache) {
  return (await preferenceServiceApi.getLastTimeGasSelection(
    chainId,
  )) as ChainGas | null;
}

export async function updateLastTimeGasSelection(
  chainId: keyof GasCache,
  gas: ChainGas,
) {
  await preferenceServiceApi.updateLastTimeGasSelection(chainId, gas);
}

export async function getLastTimeSendToken(
  ...args: Parameters<PreferenceService['getLastTimeSendToken']>
) {
  return (await preferenceServiceApi.getLastTimeSendToken(
    ...args,
  )) as ReturnType<PreferenceService['getLastTimeSendToken']>;
}

export async function setLastTimeSendToken(
  ...args: Parameters<PreferenceService['setLastTimeSendToken']>
) {
  await preferenceServiceApi.setLastTimeSendToken(...args);
}

export async function getCustomizedToken() {
  return (await preferenceServiceApi.getCustomizedToken()) as Token[];
}

export async function getBlockedToken() {
  return (await preferenceServiceApi.getBlockedToken()) as Token[];
}

export function getPinnedTokenSnapshot() {
  return getRegisteredService('preferenceService')?.getPinToken() || [];
}

export function getPinnedAddressSnapshot() {
  return getRegisteredService('preferenceService')?.getPinAddresses() || [];
}

export async function getPinnedAddresses() {
  return (await preferenceServiceApi.getPinAddresses()) as IPinAddress[];
}

export async function updatePinnedAddresses(list: IPinAddress[]) {
  await preferenceServiceApi.updatePinAddresses(list);
}

export function getNeedsBackupReminderSnapshot(basePublicKey: string) {
  return (
    getRegisteredService('preferenceService')?.getNeedsBackupReminder(
      basePublicKey,
    ) || false
  );
}

export async function setNeedsBackupReminder(
  basePublicKey: string,
  needsReminder: boolean,
) {
  await preferenceServiceApi.setNeedsBackupReminder(
    basePublicKey,
    needsReminder,
  );
}

export async function clearNeedsBackupReminder(basePublicKey: string) {
  await preferenceServiceApi.clearNeedsBackupReminder(basePublicKey);
}

export function getAddressAvatarSnapshot(address: string) {
  return getRegisteredService('preferenceService')?.getAddressAvatar(address);
}

export async function addAddressAvatar(address: string, avatar: string) {
  await preferenceServiceApi.addAddressAvatar(address, avatar);
}

export async function addCustomizedToken(token: Token) {
  return (await preferenceServiceApi.addCustomizedToken(token)) as Token | null;
}

export async function removeCustomizedToken(token: Token) {
  await preferenceServiceApi.removeCustomizedToken(token);
}

export async function addBlockedToken(token: Token) {
  await preferenceServiceApi.addBlockedToken(token);
}

export async function removeBlockedToken(token: Token) {
  await preferenceServiceApi.removeBlockedToken(token);
}

export async function setReportActionTs(
  ...args: Parameters<PreferenceService['setReportActionTs']>
) {
  await preferenceServiceApi.setReportActionTs(...args);
}

export async function getSendLogTime() {
  return (await preferenceServiceApi.getSendLogTime()) as ReturnType<
    PreferenceService['getSendLogTime']
  >;
}

export async function updateSendLogTime(
  ...args: Parameters<PreferenceService['updateSendLogTime']>
) {
  await preferenceServiceApi.updateSendLogTime(...args);
}

export type UserTokenSettings = ReturnType<
  PreferenceService['getUserTokenSettingsSync']
>;

export const EMPTY_USER_TOKEN_SETTINGS: UserTokenSettings = {
  foldTokens: [],
  unfoldTokens: [],
  includeDefiAndTokens: [],
  excludeDefiAndTokens: [],
  pinedQueue: [],
  foldNfts: [],
  unfoldNfts: [],
  foldDefis: [],
  unFoldDefis: [],
};

export function getUserTokenSettingsSnapshot() {
  return (
    getRegisteredService('preferenceService')?.getUserTokenSettingsSync() ||
    EMPTY_USER_TOKEN_SETTINGS
  );
}

export async function getUserTokenSettings() {
  return (await preferenceServiceApi.getUserTokenSettings()) as UserTokenSettings;
}

export async function setPreference(params: Partial<PreferenceStore>) {
  await preferenceServiceApi.setPreference(params);
}

export function setPreferenceSync(params: Partial<PreferenceStore>) {
  const service = getRegisteredService('preferenceService');
  if (!service) {
    throw new Error('preferenceService is not ready');
  }
  service.setPreference(params);
}

export async function setPreferenceByKey<K extends keyof PreferenceStore>(
  key: K,
  value: PreferenceStore[K],
) {
  await preferenceServiceApi.setPreferenceByKey(key, value);
}

export async function setCurrentAccount(
  ...args: Parameters<PreferenceService['setCurrentAccount']>
) {
  await preferenceServiceApi.setCurrentAccount(...args);
}

export function setCurrentAccountSync(
  ...args: Parameters<PreferenceService['setCurrentAccount']>
) {
  const service = getRegisteredService('preferenceService');
  if (!service) {
    throw new Error('preferenceService is not ready');
  }
  service.setCurrentAccount(...args);
}

export async function setPasswordIsAutoGenerated(value: boolean) {
  await preferenceServiceApi.setPasswordIsAutoGenerated(value);
}

export async function setUserBehaviorTrackingOptOut(value: boolean) {
  await preferenceServiceApi.setUserBehaviorTrackingOptOut(value);
}

export function setUserBehaviorTrackingOptOutSync(value: boolean) {
  const service = getRegisteredService('preferenceService');
  if (!service) {
    throw new Error('preferenceService is not ready');
  }
  service.setUserBehaviorTrackingOptOut(value);
}

export async function pinUserToken(
  token: Parameters<PreferenceService['pinToken']>[0],
) {
  await preferenceServiceApi.pinToken(token);
}

export async function removePinnedUserToken(
  token: Parameters<PreferenceService['removePinedToken']>[0],
) {
  await preferenceServiceApi.removePinedToken(token);
}

export async function dangerouslySetTokenManageSettingMapForDev(
  ...args: Parameters<PreferenceService['_dangerouslySetTokenManageSettingMap']>
) {
  await preferenceServiceApi._dangerouslySetTokenManageSettingMap(...args);
}
