export type ServiceSnapshotPolicy =
  | 'startup-critical'
  | 'persisted-local'
  | 'reactive'
  | 'command-input';

// Every Snapshot export must declare why a synchronous fallback is safe.
// Reactive consumers must converge after registration; command inputs should
// migrate to an awaited service API whenever their caller is already async.

type SnapshotExportNames<TModule> = {
  [TKey in keyof TModule]: TKey extends string
    ? TKey extends `${string}Snapshot${string}`
      ? TKey
      : never
    : never;
}[keyof TModule];

type SnapshotPolicies<TModule> = Record<
  SnapshotExportNames<TModule>,
  ServiceSnapshotPolicy
>;

const browser = {
  getBrowserBookmarkCountSnapshot: 'reactive',
  getBrowserBookmarkSnapshot: 'reactive',
  getBrowserHistorySnapshot: 'reactive',
  getBrowserTabCountSnapshot: 'reactive',
  getBrowserTabsSnapshot: 'reactive',
} satisfies SnapshotPolicies<typeof import('./browser')>;

const contact = {
  getContactAliasMapSnapshot: 'startup-critical',
  getContactAliasSnapshot: 'startup-critical',
  getContactsByMapSnapshot: 'startup-critical',
} satisfies SnapshotPolicies<typeof import('./contact')>;

const currency = {
  getCurrencyStoreSnapshot: 'persisted-local',
} satisfies SnapshotPolicies<typeof import('./currency')>;

const dapp = {
  getConnectedDappSnapshot: 'command-input',
  getDappSnapshot: 'reactive',
  getDappStoreSnapshot: 'reactive',
  getDappsSnapshot: 'reactive',
  hasDappPermissionSnapshot: 'command-input',
  isInternalDappSnapshot: 'command-input',
} satisfies SnapshotPolicies<typeof import('./dapp')>;

const gasAccount = {
  getGasAccountAccountsWithBalanceSnapshot: 'reactive',
  getGasAccountCurrentBalanceStateSnapshot: 'reactive',
  getGasAccountCurrentEligibleAddressSnapshot: 'reactive',
  getGasAccountDataSnapshot: 'reactive',
  getGasAccountHasClaimedGiftSnapshot: 'reactive',
  getGasAccountPendingHardwareAccountSnapshot: 'reactive',
  getGasAccountServiceGenerationSnapshot: 'startup-critical',
  getGasAccountSigSnapshot: 'command-input',
  hasGasAccountTrackedGa4ActiveTodaySnapshot: 'reactive',
} satisfies SnapshotPolicies<typeof import('./gasAccount')>;

const keyring = {
  getKeyringByTypeSnapshot: 'startup-critical',
  getKeyringClassForTypeSnapshot: 'startup-critical',
  getKeyringInstancesSnapshot: 'startup-critical',
  getKeyringMemStoreStateSnapshot: 'startup-critical',
  getKeyringVaultDebugStateSnapshot: 'startup-critical',
  getKeyringsByTypeSnapshot: 'startup-critical',
  getPublicAccountSnapshotAccounts: 'startup-critical',
  hasKeyringInstanceSnapshot: 'startup-critical',
  hasKeyringPublicAccountSnapshot: 'startup-critical',
  isKeyringBootedSnapshot: 'startup-critical',
  isKeyringRuntimeReadySnapshot: 'startup-critical',
  isKeyringUnlockedSnapshot: 'startup-critical',
} satisfies SnapshotPolicies<typeof import('./keyring')>;

const notification = {
  getCurrentMiniApprovalSnapshot: 'reactive',
  getNotificationApprovalCountSnapshot: 'reactive',
  getNotificationStatsDataSnapshot: 'command-input',
  getNotificationWindowIdSnapshot: 'reactive',
  getShouldDisplayBlockedRequestApprovalSnapshot: 'command-input',
  getShouldDisplayCancelAllApprovalSnapshot: 'command-input',
} satisfies SnapshotPolicies<typeof import('./notification')>;

const offlineChain = {
  getCloseTipsChainsSnapshot: 'reactive',
} satisfies SnapshotPolicies<typeof import('./offlineChain')>;

const preference = {
  getAddressAvatarSnapshot: 'startup-critical',
  getFallbackAccountSnapshot: 'startup-critical',
  getIsShowTestnetSnapshot: 'startup-critical',
  getNeedsBackupReminderSnapshot: 'startup-critical',
  getPasswordIsAutoGeneratedSnapshot: 'startup-critical',
  getPinnedAddressSnapshot: 'startup-critical',
  getPinnedTokenSnapshot: 'startup-critical',
  getPreferenceSnapshot: 'startup-critical',
  getTokenDisplayModeSnapshot: 'startup-critical',
  getUserTokenSettingsSnapshot: 'startup-critical',
  getWatchlistSkipSnapshot: 'startup-critical',
} satisfies SnapshotPolicies<typeof import('./preference')>;

const transactionHistory = {
  getTransactionHistoryClearSuccessAndFailListTsSnapshot: 'reactive',
  getTransactionHistoryCustomTxItemMapSnapshot: 'reactive',
  getTransactionHistoryFailedCountSnapshot: 'reactive',
  getTransactionHistoryLendingSuccessListSnapshot: 'reactive',
  getTransactionHistoryListSnapshot: 'reactive',
  getTransactionHistoryPendingsAddressesSnapshot: 'reactive',
  getTransactionHistoryRecentPendingSnapshot: 'reactive',
  getTransactionHistoryRecentTxSnapshot: 'reactive',
  getTransactionHistorySendListSnapshot: 'reactive',
  getTransactionHistorySucceedCountSnapshot: 'reactive',
  getTransactionHistorySucceedListSnapshot: 'reactive',
  getTransactionHistorySwapFailTransactionsSnapshot: 'reactive',
} satisfies SnapshotPolicies<typeof import('./transactionHistory')>;

export const CORE_SERVICE_SNAPSHOT_POLICIES = {
  browser,
  contact,
  currency,
  dapp,
  gasAccount,
  keyring,
  notification,
  offlineChain,
  preference,
  transactionHistory,
} as const;
