name: Build and deploy iOS release
on:
  push:
    tags:
      - 'ios-release-*'
    branches:
      - 'ci/ios-release-*'
      - ci/universal-release-*
  workflow_dispatch:
    inputs:
      REALLY_UPLOAD:
        required: true
        type: boolean
        default: true
      SENTRY_DISABLE_AUTO_UPLOAD:
        required: true
        type: boolean
        default: false
      macos_machine_location:
        required: true
        type: choice
        options:
          - 'mobile'
          - 'mobile-local'
        default: 'mobile'
      NEW_VERSION_NAME:
        required: false
        type: string
        default: ''
  workflow_call:
    secrets:
      KEYCHAIN_PASS:
        required: true

defaults:
  run:
    shell: bash -ieol pipefail {0}

env:
  BUILD_TARGET_PLATFORM: ios

jobs:
  setup:
    name: iOS-release-build
    environment: Production
    strategy:
      matrix:
        include:
          - host: macOS
            machine_loc: ${{ inputs.macos_machine_location }}
    runs-on:
      - self-hosted
      - ${{ matrix.host }}
      - ${{ matrix.machine_loc }}
    env:
      RABBY_MOBILE_NM_USE_CACHE: 'true'
      XCODE_VER: '26.3'
    steps:
      - name: Checkout git repo
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          clean: false

      - name: Clean git Manually
        run: |
          yarn_exclude_args=()
          if [ "$RABBY_MOBILE_NM_USE_CACHE" = "true" ]; then
            echo "Keep yarn install outputs";
            yarn_exclude_args+=(
              -e node_modules
              -e 'apps/*/node_modules'
              -e 'packages/*/node_modules'
              -e .yarn/install-state.gz
              -e .yarn/unplugged
            )
          fi

          git clean -ffdx "${yarn_exclude_args[@]}";
          git reset --hard HEAD;

      - name: Env Test
        id: env-test
        run: |
          echo "whoami $(whoami)"
          echo "shell is $(echo $0)"
          echo "HOME is $HOME"
          echo "which node $(which node)"

      - name: Get Actions Variables
        id: actionvars
        shell: bash
        run: |
          trigger_date=$(date +'%Y%m%d%H%M%S')
          echo "trigger_date=$trigger_date" >> "$GITHUB_OUTPUT"

          flatten_refname=${GITHUB_REF_NAME//\//'_'}
          flatten_refname=${flatten_refname//\./'_'}
          echo "flatten_refname=$flatten_refname" >> "$GITHUB_OUTPUT"

      # - name: Setup Nodejs and Yarn
      #   uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3
      #   with:
      #     node-version: 22

      # - name: Setup Ruby & Fastlane
      #   uses: ruby/setup-ruby@c4e5b1316158f92e3d49443a9d58b31d25ac0f8f # v1
      #   with:
      #     ruby-version: '2.7'
      #     bundler-cache: true # runs 'bundle install' and caches installed gems automatically

      - uses: maxim-lobanov/setup-xcode@ed7a3b1fda3918c0306d1b724322adc0b8cc0a90 # v1
        id: setup-xcode
        with:
          # use specific version rather than 'latest-stable' if multiple Xcodes installed
          xcode-version: ${{ env.XCODE_VER }}

      - name: Enable Corepack
        run: corepack enable

      - name: Install dependencies && Build app
        run: |
          cd apps/mobile;
          RABBY_MOBILE_RUN_POSTINSTALL=true bash ./scripts/ci/prepare-mobile-build.sh;

          if [ "$INPUT_MOBILE_LOC" != "mobile-local" ]; then
            RABBY_MOBILE_UNLOCK_KEYCHAIN_PASS=${{ secrets.KEYCHAIN_PASS }}
          fi
          # security unlock-keychain -p $RABBY_MOBILE_UNLOCK_KEYCHAIN_PASS ~/Library/Keychains/login.keychain-db
          security unlock-keychain -p $RABBY_MOBILE_UNLOCK_KEYCHAIN_PASS login.keychain
          ./scripts/deploy-ios-appstore.sh

        env:
          KEYCHAIN_PASS: ${{ secrets.KEYCHAIN_PASS }}
          RABBY_MOBILE_BUILD_BUCKET: ${{ secrets.RABBY_MOBILE_BUILD_BUCKET }}
          RABBY_MOBILE_KR_PWD: ${{ secrets.RABBY_MOBILE_KR_PWD }}
          RABBY_MOBILE_SAFE_API_KEY: ${{ secrets.MOBILE_SAFE_API_KEY }}
          RABBY_MOBILE_CODE: ${{ secrets.RABBY_MOBILE_CODE2 }}
          RABBY_MOBILE_SENTRY_AUTH_TOKEN2: ${{ secrets.RABBY_MOBILE_SENTRY_AUTH_TOKEN2 }}
          SENTRY_AUTH_TOKEN: ${{ secrets.RABBY_MOBILE_SENTRY_AUTH_TOKEN2 }}
          MATCH_PASSWORD: ${{ secrets.RABBY_MOBILE_MATCH_PASSWORD }}
          INPUT_MOBILE_LOC: ${{ inputs.macos_machine_location }}
          REALLY_UPLOAD: ${{ inputs.REALLY_UPLOAD }}
          SENTRY_DISABLE_AUTO_UPLOAD: ${{ inputs.SENTRY_DISABLE_AUTO_UPLOAD }}
          CONFIGURATION: release
          TYPE: appstore
          RABBY_MOBILE_BUILD_ENV: production
          RABBY_MOBILE_ASC_API_KEY_ID: ${{ secrets.RABBY_MOBILE_ASC_API_KEY_ID }}
          RABBY_MOBILE_ASC_API_ISSUER_ID: ${{ secrets.RABBY_MOBILE_ASC_API_ISSUER_ID }}
          RABBY_MOBILE_ASC_API_PRIVATE_KEY_BASE64: ${{ secrets.RABBY_MOBILE_ASC_API_PRIVATE_KEY_BASE64 }}
          RABBY_MOBILE_LARK_CHAT_URL: ${{ secrets.LARK_CHAT_URL }}
          RABBY_MOBILE_LARK_CHAT_SECRET: ${{ secrets.LARK_CHAT_SECRET }}
          RABBY_ROBOT_LARK_APP_ID: ${{ secrets.RABBY_ROBOT_LARK_APP_ID }}
          RABBY_ROBOT_LARK_APP_SECRET: ${{ secrets.RABBY_ROBOT_LARK_APP_SECRET }}
          # see more details on https://docs.github.com/en/actions/learn-github-actions/contexts#github-context
          GIT_ACTIONS_JOB_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TRIGGERING_ACTOR: ${{ github.triggering_actor }}
          GIT_COMMIT_URL: ${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}
          GIT_REF_NAME: ${{ github.ref_name }}
          GIT_REF_URL: ${{ github.server_url }}/${{ github.repository }}/tree/${{ github.ref_name }}
          GITHUB_REF: ${{ github.ref }}
          INPUT_NEW_VERSION_NAME: ${{ inputs.NEW_VERSION_NAME }}

      # - name: Upload artifact
      #   uses: actions/upload-artifact@ff15f0306b3f739f7b6fd43fb5d26cd321bd4de5 # v3
      #   with:
      #     name: rabbymobile-${{ steps.actionvars.outputs.flatten_refname }}-${{ steps.actionvars.outputs.trigger_date }}
      #     path: |
      #       ./apps/mobile/ios/Package/appstore/*.ipa
      #       ./apps/mobile/ios/Package/appstore/*.zip
      #     retention-days: 90
